In [1]:
import pandas as pd

In [4]:
water_level = pd.read_csv('C:/Users/welcome/Desktop/CHARAN/Supervised learning/data/chennai/chennai_reservoir_levels.csv')

In [5]:
water_level.head()

Date  POONDI  CHOLAVARAM  REDHILLS  CHEMBARAMBAKKAM
0  01-01-2004     3.9         0.0     268.0              0.0
1  02-01-2004     3.9         0.0     268.0              0.0
2  03-01-2004     3.9         0.0     267.0              0.0
3  04-01-2004     3.9         0.0     267.0              0.0
4  05-01-2004     3.8         0.0     267.0              0.0

# Pre - Processing 'Date' Variable

In [19]:
import numpy as np

In [20]:
wlevel_num=water_level.select_dtypes(include=[np.number])
wlevel_char=water_level.select_dtypes(include=[object])

In [21]:
wlevel_num.head()

POONDI  CHOLAVARAM  REDHILLS  CHEMBARAMBAKKAM
0     3.9         0.0     268.0              0.0
1     3.9         0.0     268.0              0.0
2     3.9         0.0     267.0              0.0
3     3.9         0.0     267.0              0.0
4     3.8         0.0     267.0              0.0

In [22]:
wlevel_char.head()

Date
0  01-01-2004
1  02-01-2004
2  03-01-2004
3  04-01-2004
4  05-01-2004

# Pre-processing categorical variables

In [25]:
wlevel_num.isnull().sum()

POONDI             0
CHOLAVARAM         0
REDHILLS           0
CHEMBARAMBAKKAM    0
dtype: int64

In [26]:
wlevel_char.isnull().sum()

Date    0
dtype: int64

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
le = LabelEncoder()

In [29]:
wlevel_char = wlevel_char.apply(le.fit_transform)

In [30]:
wlevel_final = pd.concat([wlevel_num,wlevel_char],axis=1)

In [31]:
wlevel_final.head()

POONDI  CHOLAVARAM  REDHILLS  CHEMBARAMBAKKAM  Date
0     3.9         0.0     268.0              0.0     0
1     3.9         0.0     268.0              0.0   189
2     3.9         0.0     267.0              0.0   378
3     3.9         0.0     267.0              0.0   567
4     3.8         0.0     267.0              0.0   756

In [33]:
wlevel_final.head()

POONDI  CHOLAVARAM  REDHILLS  CHEMBARAMBAKKAM  Date
0     3.9         0.0     268.0              0.0     0
1     3.9         0.0     268.0              0.0   189
2     3.9         0.0     267.0              0.0   378
3     3.9         0.0     267.0              0.0   567
4     3.8         0.0     267.0              0.0   756

# Train model  and prediction for DATE AND PONDI

In [119]:
from sklearn.model_selection import train_test_split

In [134]:
x=pd.DataFrame(wlevel_final['Date'])

In [135]:
y=pd.DataFrame(wlevel_final['POONDI'])

In [136]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=9)

In [137]:
from sklearn.linear_model import LinearRegression

In [138]:
lr= LinearRegression()

In [139]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [140]:
pre=lr.predict(x_test)

In [141]:
from sklearn.metrics import mean_squared_error

In [142]:
from sklearn.metrics import r2_score

In [143]:
test_set_rmse = (np.sqrt(mean_squared_error(y_test, pre)))

In [144]:
print(test_set_rmse)

1032.2354888738912


In [145]:
test_set_r2 = r2_score(y_test, pre)

In [146]:
print(test_set_r2)

-0.0005867680531175257


# Fit 

In [147]:
pre


array([[1116.7989858 ],
       [1116.74582032],
       [1120.59453854],
       ...,
       [1120.52750381],
       [1124.75069191],
       [1119.98429133]])

In [148]:
fit = lr.fit(x,y)

In [149]:
fit.score(x,y)

3.07750876720192e-05

# Train model  and prediction for DATE AND CHOOLAVARAM

In [150]:
from sklearn.model_selection import train_test_split

In [151]:
x=pd.DataFrame(wlevel_final['Date'])

In [153]:
y=pd.DataFrame(wlevel_final['CHOLAVARAM'])

In [154]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=9)

In [155]:
from sklearn.linear_model import LinearRegression

In [156]:
lr= LinearRegression()

In [157]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [158]:
pre=lr.predict(x_test)

In [159]:
from sklearn.metrics import mean_squared_error

In [160]:
from sklearn.metrics import r2_score

In [162]:
test_set_rmse = (np.sqrt(mean_squared_error(y_test, pre)))
test_set_r2 = r2_score(y_test, pre)

In [172]:
print(test_set_rmse)
print("Accuracy:",test_set_r2)


271.733157231263
Accuracy: -0.0003539685619338151


# Train model  and prediction for DATE AND REDHILLS

In [167]:
from sklearn.model_selection import train_test_split

In [168]:
x=pd.DataFrame(wlevel_final['Date'])

In [169]:
y=pd.DataFrame(wlevel_final['REDHILLS'])

In [170]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=9)

In [173]:
from sklearn.linear_model import LinearRegression

In [174]:
lr= LinearRegression()

In [175]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [176]:
pre=lr.predict(x_test)

In [201]:
pre

array([[1301.23907205],
       [1301.13801238],
       [1308.4538537 ],
       ...,
       [1308.32643064],
       [1316.35408354],
       [1307.29386445]])

In [178]:
from sklearn.metrics import mean_squared_error

In [179]:
from sklearn.metrics import r2_score

In [180]:
test_set_rmse = (np.sqrt(mean_squared_error(y_test, pre)))
test_set_r2 = r2_score(y_test, pre)

In [181]:
print(test_set_rmse)
print("Accuracy:",test_set_r2)

914.4940251508382
Accuracy: -0.0007834978024627848


# Train model  and prediction for DATE AND CHEMBARAMBAKKAM

In [183]:
from sklearn.model_selection import train_test_split

In [184]:
x=pd.DataFrame(wlevel_final['Date'])

In [186]:
y=pd.DataFrame(wlevel_final['CHEMBARAMBAKKAM'])

In [187]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=9)

In [188]:
from sklearn.linear_model import LinearRegression

In [189]:
lr= LinearRegression()

In [190]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [191]:
pre=lr.predict(x_test)

In [200]:
pre

array([[1301.23907205],
       [1301.13801238],
       [1308.4538537 ],
       ...,
       [1308.32643064],
       [1316.35408354],
       [1307.29386445]])

In [192]:
from sklearn.metrics import mean_squared_error

In [193]:
from sklearn.metrics import r2_score

In [194]:
test_set_rmse = (np.sqrt(mean_squared_error(y_test, pre)))
test_set_r2 = r2_score(y_test, pre)

In [196]:
print(test_set_rmse)
print("Accuracy:",test_set_r2)

967.8947370824542
Accuracy: -0.0013468856944225394


In [199]:
wlevel_final.head


<bound method NDFrame.head of       POONDI  CHOLAVARAM  REDHILLS  CHEMBARAMBAKKAM  Date
0        3.9         0.0     268.0              0.0     0
1        3.9         0.0     268.0              0.0   189
2        3.9         0.0     267.0              0.0   378
3        3.9         0.0     267.0              0.0   567
4        3.8         0.0     267.0              0.0   756
5        3.8         0.0     266.0              0.0   945
6        3.8         0.0     266.0              0.0  1134
7        3.7         0.0     265.0              0.0  1323
8        3.7         0.0     264.0              0.0  1512
9        3.7         0.0     264.0              0.0  1701
10       3.6         0.0     263.0              0.0  1890
11       3.6         0.0     262.0              0.0  2079
12       3.6         0.0     261.0              0.0  2268
13       3.5         0.0     260.0              0.0  2457
14       3.5         0.0     259.0              0.0  2646
15       3.4         0.0     258.0        